# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "shoot-grafter"
SPDX-PackageDownloadLocation = "https://github.com/cloudoperators/shoot-grafter"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
]
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company and Greenhouse contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "*/zz_generated.deepcopy.go",
  "crd/*",
]
